import React, { createContext, useContext, useState } from 'react';

type Language = 'az' | 'ru' | 'en' | 'uz';

type LanguageContextType = {
  language: Language;
  changeLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['az']) => string;
};

const translations = {
  az: {
    home: "Ana Səhifə",
    collections: "Kolleksiyalar",
    club: "BirBuketClub",
    create_bouquet: "BirBuket Yarat",
    gardener: "BirBağban",
    about: "Haqqımızda",
    bagban_panel: "Bağban Paneli",
    florist_panel: "Florist Paneli",
    login: "Daxil ol",
    register: "Qeydiyyat",
    logout: "Çıxış",
    profile: "Hesabım",
    cart: "Səbət",
    profile_info: "Profil məlumatlarım",
    order_history: "Sifariş tarixçəm",
    favorites: "Sevimlilərim",
    gardener_requests: "Bağban müraciətləri",
    services_title: "Xidmətlərimiz",
    services_subtitle: "Sizin üçün ən yaxşı xidməti təklif etmək məqsədilə hər detala diqqət yetiririk.",
    loading_api: "Məlumatlar API-dan alınır...",
    
    // Hero Section
    premium_service: "Premium Çiçək Xidməti",
    hero_title_1: "Hər Çiçəkdə",
    hero_title_italic: "Bir Hekayə",
    hero_title_2: "Var",
    hero_desc: "Təbii güllər, estetik dibçək bitkiləri və unudulmaz tədbirləriniz üçün xüsusi dizayn edilmiş dekorasiyalar. Sizin sevginizi çiçəklərlə ifadə edirik.",
    order_now: "İndi sifariş et",
    view_collections: "Kolleksiyalara bax",
    fresh_species: "45+ növ",
    fresh_desc: "Təzə kəsilmiş gül növləri hər gün anbarda",

    // About Section
    about_title: "BirBuket - hisslərin ən zərif ifadəsi",
    about_desc: "BirBuket olaraq məqsədimiz sevdiklərinizə çatacaq hər buketi xüsusi etməkdir. Platformamız vasitəsilə siz həm sürətli sifariş verə, həm də sifarişinizin çatdırılma mərhələsini rahat izləyə bilərsiniz.",
    why_choose_us: "Nəyə görə bizi seçirlər?",
    why_choose_li_1: "- Geniş buket çeşidləri və fərdi dizayn imkanı",
    why_choose_li_2: "- Rahat ödəniş və sadə sifariş prosesi",
    why_choose_li_3: "- Müştəri məmnuniyyətinə fokuslanan dəstək xidməti",
    
    hl_title_1: "Təzə güllər",
    hl_desc_1: "Kompozisiyalar gündəlik seçilən təzə güllərlə hazırlanır.",
    hl_title_2: "Sürətli çatdırılma",
    hl_desc_2: "Bakı daxili çatdırılma: məsafəyə görə 5–20 AZN (4 km-ə qədər 5 AZN; 15 km-dən çox 20 AZN). Vaxtında və təhlükəsiz çatdırılma.",
    hl_title_3: "Fərdi yanaşma",
    hl_desc_3: "Hər buket istəyinizə uyğun zövqlə formalaşdırılır.",
    hl_title_4: "Etibarlı xidmət",
    hl_desc_4: "Sifarişdən təhvila qədər hər addımda şəffaf proses.",

    // Footer Section
    footer_desc: "Bakıda ən təzə və keyfiyyətli güllərin tək ünvanı. Sevdiklərinizi sevindirmək üçün biz buradayıq.",
    catalog: "Kataloq",
    services: "Xidmətlər",
    support: "Dəstək",
    write_to_us: "Bizə yazın",
    newsletter_desc: "Yeniliklərdən və kampaniyalardan xəbərdar olun.",
    all_products: "Bütün Məhsullar",
    toy_decor: "Toy dekorasiyası",
    faq: "Suallar",
    delivery_rules: "Çatdırılma qaydaları",
    returns: "Geri qaytarılma",
    contact: "Əlaqə",
    rights_reserved: "© 2024 BirBuket. Bütün hüquqlar qorunur.",
    privacy_policy: "Məxfilik siyasəti",
    terms_of_use: "İstifadə şərtləri",

    // Auth / Login & Register
    login_heading: "Hesabınıza daxil olun",
    login_sub: "Davam etmək üçün e-poçt və şifrənizi daxil edin",
    email_or_user: "E-poçt və ya istifadəçi adı",
    email_or_user_placeholder: "Email və ya username",
    password_label: "Şifrə",
    forgot_password: "Şifrəni unutmusunuz?",
    remember_me: "Məni xatırla",
    dont_have_account: "Hesabınız yoxdur?",
    signup_link: "Qeydiyyatdan keçin",
    login_hero_title: "Sevdikləriniz üçün gülü seçin, sifarişi rahat izləyin",
    login_hero_desc: "BirBuket hesabınızla buket seçin, ünvanı qeyd edin və çatdırılma statusunu addım-addım izləyin.",
    login_feat_1: "Fərdi hesabda sifariş tarixçənizi toplayın",
    login_feat_2: "Ünvan, alıcı və çatdırılma qeydlərini rahat idarə edin",
    login_feat_3: "Sifariş hazırlanır, yoldadır, çatdırıldı statuslarını izləyin",
    login_feat_4: "Onlayn ödəniş və sifariş detallarına bir toxunuşla baxın",

    name_label: "Ad",
    surname_label: "Soyad",
    name_placeholder: "Adınız",
    surname_placeholder: "Soyadınız",
    gender_label: "Cinsiyyət",
    gender_male: "Kişi",
    gender_female: "Qadın",
    birth_date_label: "Təvəllüd",
    username_label: "İstifadəçi adı",
    phone_label: "Telefon nömrəsi",
    email_label: "E-poçt",
    password_confirm_label: "Şifrəni təsdiqlə",
    register_heading: "Qeydiyyat",
    register_sub: "BirBuket ailəsinə qoşulun",
    register_btn: "Hesab yarat",
    already_have_account: "Artıq hesabınız var?",
    login_link: "Daxil olun",

    // BirBuketClub
    club_title: "BirBuketClub",
    club_subscriptions: "Abunəliklər",
    club_flowers: "Güllər",
    club_studio: "Studio",
    club_sub_desc: "Gül abunəliyi ilə hər həftə və ya hər ay qapınıza gələn təzə çiçəklərin sevincini yaşayın.",
    club_sub_title: "Evinizə Həmişə Təravət Gəlsin",
    club_btn_start: "İndi Başla",
    club_btn_setup: "Abunəliyi Qurun",
    club_active_plan: "Aktiv plan:",
    club_subscribers: "1200+ Abunəçi",
    club_plans_title: "Abunəlik Planları",
    club_plans_sub: "Ehtiyacınıza uyğun olanı seçin",
    club_popular: "Populyar",
    club_select: "Seç",
    club_selected: "Seçildi",
    club_setup_title: "Abunəliyinizi Qurun",
    club_setup_sub: "Cəmi 3 addımla abunəliyi tamamlayın",
    club_step_1: "Üslub & Tezlik",
    club_step_2: "Məlumatlar",
    club_step_3: "Təsdiq & Ödəniş",
    club_step_style_title: "1. Buket Üslubunu Seçin",
    club_step_freq_title: "2. Çatdırılma Tezliyi",
    club_btn_next: "Məlumatları Daxil Et (Növbəti Addım)",
    club_delivery_info: "3. Çatdırılma Məlumatları",
    club_recipient_name: "Alıcının Adı və Soyadı",
    club_recipient_name_placeholder: "Məs. Əli Məmmədov",
    club_phone: "Əlaqə Telefonu",
    club_phone_placeholder: "Məs. +994 50 123 45 67",
    club_address: "Çatdırılma Ünvanı",
    club_address_placeholder: "Məs. Nəsimi rayonu, Səməd Vurğun küçəsi, ev 45, mənzil 12",
    club_date: "İlk Çatdırılma Tarixi",
    club_btn_prev: "Geri",
    club_btn_next_summary: "İrəli (Xülasə)",
    club_step_confirm_title: "4. Təsdiq & Ödəniş",
    club_confirm_sub: "Abunəlik Təsdiqi:",
    club_confirm_desc: "Seçdiyiniz plan üzrə hər ödəniş dövründə avtomatik yenilənmə ediləcəkdir. İlk çatdırılma yaxın günlərdə yerinə yetiriləcək.",
    club_confirm_tip: "Floristimiz hər dəfə ən təzə mövsümi çiçəklərdən buket hazırlayacaq.",
    club_btn_activate: "Abunəliyi Aktiv Et",
    club_btn_activating: "Aktiv edilir...",
    club_summary_title: "Sifariş Xülasəsi",
    club_summary_plan: "Plan:",
    club_summary_style: "Üslub:",
    club_summary_freq: "Tezlik:",
    club_summary_recipient: "Alıcı:",
    club_summary_address: "Ünvan:",
    club_summary_delivery: "Çatdırılma:",
    club_summary_free: "Pulsuz",
    club_summary_total: "Toplam:",
    club_security_tip: "Ödənişləriniz təhlükəsizdir. İstənilən vaxt planı dəyişə və ya dayandıra bilərsiniz.",
  },
  ru: {
    home: "Главная",
    collections: "Коллекции",
    club: "BirBuketClub",
    create_bouquet: "Создать букет",
    gardener: "BirBağban",
    about: "О нас",
    bagban_panel: "Панель садовника",
    florist_panel: "Панель флориста",
    login: "Войти",
    register: "Регистрация",
    logout: "Выход",
    profile: "Профиль",
    cart: "Корзина",
    profile_info: "Информация профиля",
    order_history: "История заказов",
    favorites: "Избранное",
    gardener_requests: "Запросы садовнику",
    services_title: "Наши услуги",
    services_subtitle: "Мы уделяем внимание каждой детали, чтобы предложить вам наилучший сервис.",
    loading_api: "Получение данных из API...",
    
    // Hero Section
    premium_service: "Премиальный цветочный сервис",
    hero_title_1: "В каждом цветке",
    hero_title_italic: "своя история",
    hero_title_2: "есть",
    hero_desc: "Свежие цветы, эстетичные комнатные растения и авторские декорации для ваших незабываемых событий. Выражаем вашу любовь цветами.",
    order_now: "Заказать сейчас",
    view_collections: "Смотреть коллекции",
    fresh_species: "45+ видов",
    fresh_desc: "Свежесрезанные сорта цветов каждый день в наличии",

    // About Section
    about_title: "BirBuket - нежнейшее выражение чувств",
    about_desc: "Наша цель в BirBuket — сделать особенным каждый букет, доставленный вашим близким. Через нашу платформу вы можете сделать быстрый заказ и легко отслеживать статус доставки.",
    why_choose_us: "Почему выбирают нас?",
    why_choose_li_1: "- Широкий выбор букетов и возможность индивидуального дизайна",
    why_choose_li_2: "- Удобная оплата и простой процесс заказа",
    why_choose_li_3: "- Служба поддержки, ориентированная на удовлетворенность клиентов",
    
    hl_title_1: "Свежие цветы",
    hl_desc_1: "Композиции создаются из свежих цветов, выбираемых ежедневно.",
    hl_title_2: "Быстрая доставка",
    hl_desc_2: "Доставка по Баку: 5–20 AZN в зависимости от расстояния (до 4 км — 5 AZN; более 15 км — 20 AZN). Своевременная и безопасная доставка.",
    hl_title_3: "Индивидуальный подход",
    hl_desc_3: "Каждый букет оформляется со вкусом в соответствии с вашими пожеланиями.",
    hl_title_4: "Надежный сервис",
    hl_desc_4: "Прозрачный процесс на каждом этапе от заказа до доставки.",

    // Footer Section
    footer_desc: "Единственный адрес самых свежих и качественных цветов в Баку. Мы здесь, чтобы радовать ваших близких.",
    catalog: "Каталог",
    services: "Услуги",
    support: "Поддержка",
    write_to_us: "Напишите нам",
    newsletter_desc: "Будьте в курсе новостей и акций.",
    all_products: "Все товары",
    toy_decor: "Свадебный декор",
    faq: "Вопросы",
    delivery_rules: "Правила доставки",
    returns: "Возврат",
    contact: "Контакты",
    rights_reserved: "© 2024 BirBuket. Все права защищены.",
    privacy_policy: "Политика конфиденциальности",
    terms_of_use: "Условия использования",

    // Auth / Login & Register
    login_heading: "Войти в аккаунт",
    login_sub: "Введите адрес электронной почты и пароль, чтобы продолжить",
    email_or_user: "Email или имя пользователя",
    email_or_user_placeholder: "Email или username",
    password_label: "Пароль",
    forgot_password: "Забыли пароль?",
    remember_me: "Запомнить меня",
    dont_have_account: "Нет учетной записи?",
    signup_link: "Зарегистрироваться",
    login_hero_title: "Выбирайте цветы для любимых и легко отслеживайте заказ",
    login_hero_desc: "Выбирайте букет с аккаунтом BirBuket, указывайте адрес и шаг за шагом следите за статусом доставки.",
    login_feat_1: "Собирайте историю заказов в личном кабинете",
    login_feat_2: "Управляйте адресами, получателями и заметками к доставке",
    login_feat_3: "Отслеживайте статусы: готовится, в пути, доставлено",
    login_feat_4: "Онлайн-оплата и детали заказа в одно касание",

    name_label: "Имя",
    surname_label: "Фамилия",
    name_placeholder: "Ваше имя",
    surname_placeholder: "Ваша фамилия",
    gender_label: "Пол",
    gender_male: "Мужской",
    gender_female: "Женский",
    birth_date_label: "Дата рождения",
    username_label: "Имя пользователя",
    phone_label: "Номер телефона",
    email_label: "Электронная почта",
    password_confirm_label: "Подтвердите пароль",
    register_heading: "Регистрация",
    register_sub: "Присоединяйтесь к семье BirBuket",
    register_btn: "Создать аккаунт",
    already_have_account: "Уже есть аккаунт?",
    login_link: "Войти",

    // BirBuketClub
    club_title: "BirBuketClub",
    club_subscriptions: "Подписки",
    club_flowers: "Цветы",
    club_studio: "Студия",
    club_sub_desc: "Испытайте радость от свежих цветов, доставляемых к вашей двери каждую неделю или каждый месяц с подпиской на цветы.",
    club_sub_title: "Пусть свежесть всегда приходит в ваш дом",
    club_btn_start: "Начать сейчас",
    club_btn_setup: "Настроить подписку",
    club_active_plan: "Активный план:",
    club_subscribers: "1200+ Подписчиков",
    club_plans_title: "Планы подписки",
    club_plans_sub: "Выберите то, что подходит именно вам",
    club_popular: "Популярный",
    club_select: "Выбрать",
    club_selected: "Выбрано",
    club_setup_title: "Настройте вашу подписку",
    club_setup_sub: "Завершите подписку всего за 3 шага",
    club_step_1: "Стиль и частота",
    club_step_2: "Информация",
    club_step_3: "Подтверждение и оплата",
    club_step_style_title: "1. Выберите стиль букета",
    club_step_freq_title: "2. Частота доставки",
    club_btn_next: "Ввести информацию (следующий шаг)",
    club_delivery_info: "3. Информация о доставке",
    club_recipient_name: "Имя и фамилия получателя",
    club_recipient_name_placeholder: "Напр. Али Мамедов",
    club_phone: "Контактный телефон",
    club_phone_placeholder: "Напр. +994 50 123 45 67",
    club_address: "Адрес доставки",
    club_address_placeholder: "Напр. Насиминский район, улица Самеда Вургуна, дом 45, кв. 12",
    club_date: "Дата первой доставки",
    club_btn_prev: "Назад",
    club_btn_next_summary: "Вперед (сводка)",
    club_step_confirm_title: "4. Подтверждение и оплата",
    club_confirm_sub: "Подтверждение подписки:",
    club_confirm_desc: "Продление будет производиться автоматически в каждый период оплаты по выбранному плану. Первая доставка будет осуществлена в ближайшие дни.",
    club_confirm_tip: "Наш флорист каждый раз будет создавать букет из самых свежих сезонных цветов.",
    club_btn_activate: "Активировать подписку",
    club_btn_activating: "Активация...",
    club_summary_title: "Сводка заказа",
    club_summary_plan: "План:",
    club_summary_style: "Стиль:",
    club_summary_freq: "Частота:",
    club_summary_recipient: "Получатель:",
    club_summary_address: "Адрес:",
    club_summary_delivery: "Доставка:",
    club_summary_free: "Бесплатно",
    club_summary_total: "Итого:",
    club_security_tip: "Ваши платежи в безопасности. Вы можете изменить или приостановить план в любое время.",
  },
  en: {
    home: "Home",
    collections: "Collections",
    club: "BirBuketClub",
    create_bouquet: "Create Bouquet",
    gardener: "BirBağban",
    about: "About Us",
    bagban_panel: "Gardener Panel",
    florist_panel: "Florist Panel",
    login: "Login",
    register: "Register",
    logout: "Log Out",
    profile: "Profile",
    cart: "Cart",
    profile_info: "Profile info",
    order_history: "Order history",
    favorites: "Favorites",
    gardener_requests: "Gardener requests",
    services_title: "Our Services",
    services_subtitle: "We pay attention to every detail to offer you the best service.",
    loading_api: "Fetching data from API...",
    
    // Hero Section
    premium_service: "Premium Flower Service",
    hero_title_1: "In Every Flower",
    hero_title_italic: "A Story",
    hero_title_2: "There Is",
    hero_desc: "Fresh flowers, aesthetic indoor plants and custom-designed decorations for your unforgettable events. We express your love with flowers.",
    order_now: "Order now",
    view_collections: "View collections",
    fresh_species: "45+ species",
    fresh_desc: "Freshly cut flower species in stock daily",

    // About Section
    about_title: "BirBuket - the finest expression of feelings",
    about_desc: "As BirBuket, our goal is to make every bouquet delivered to your loved ones special. Through our platform, you can place quick orders and easily track the delivery stage.",
    why_choose_us: "Why choose us?",
    why_choose_li_1: "- Wide range of bouquets and individual design options",
    why_choose_li_2: "- Convenient payment and simple ordering process",
    why_choose_li_3: "- Customer satisfaction-focused support service",
    
    hl_title_1: "Fresh flowers",
    hl_desc_1: "Arrangements are made with fresh flowers selected daily.",
    hl_title_2: "Fast delivery",
    hl_desc_2: "Delivery within Baku: 5–20 AZN depending on distance (up to 4 km is 5 AZN; over 15 km is 20 AZN). Timely and safe delivery.",
    hl_title_3: "Individual approach",
    hl_desc_3: "Every bouquet is tastefully designed according to your request.",
    hl_title_4: "Reliable service",
    hl_desc_4: "Transparent process at every step from order to delivery.",

    // Footer Section
    footer_desc: "The only address for the freshest and highest quality flowers in Baku. We are here to make your loved ones happy.",
    catalog: "Catalog",
    services: "Services",
    support: "Support",
    write_to_us: "Write to us",
    newsletter_desc: "Stay informed about news and campaigns.",
    all_products: "All Products",
    toy_decor: "Wedding decoration",
    faq: "FAQ",
    delivery_rules: "Delivery rules",
    returns: "Returns",
    contact: "Contact",
    rights_reserved: "© 2024 BirBuket. All rights reserved.",
    privacy_policy: "Privacy policy",
    terms_of_use: "Terms of use",

    // Auth / Login & Register
    login_heading: "Log in to your account",
    login_sub: "Enter your email and password to continue",
    email_or_user: "Email or Username",
    email_or_user_placeholder: "Email or username",
    password_label: "Password",
    forgot_password: "Forgot Password?",
    remember_me: "Remember me",
    dont_have_account: "Don't have an account?",
    signup_link: "Sign up",
    login_hero_title: "Choose flowers for loved ones and track order easily",
    login_hero_desc: "Choose a bouquet with BirBuket account, specify address and track delivery status step-by-step.",
    login_feat_1: "Collect order history in personal account",
    login_feat_2: "Easily manage address, recipient and delivery notes",
    login_feat_3: "Track status: preparing, on the way, delivered",
    login_feat_4: "Online payment and order details in one touch",

    name_label: "Name",
    surname_label: "Surname",
    name_placeholder: "Your name",
    surname_placeholder: "Your surname",
    gender_label: "Gender",
    gender_male: "Male",
    gender_female: "Female",
    birth_date_label: "Birth Date",
    username_label: "Username",
    phone_label: "Phone number",
    email_label: "Email",
    password_confirm_label: "Confirm Password",
    register_heading: "Register",
    register_sub: "Join the BirBuket family",
    register_btn: "Create account",
    already_have_account: "Already have an account?",
    login_link: "Login",

    // BirBuketClub
    club_title: "BirBuketClub",
    club_subscriptions: "Subscriptions",
    club_flowers: "Flowers",
    club_studio: "Studio",
    club_sub_desc: "Experience the joy of fresh flowers delivered to your door every week or every month with a flower subscription.",
    club_sub_title: "Let freshness always come to your home",
    club_btn_start: "Start Now",
    club_btn_setup: "Setup Subscription",
    club_active_plan: "Active plan:",
    club_subscribers: "1200+ Subscribers",
    club_plans_title: "Subscription Plans",
    club_plans_sub: "Choose what suits you best",
    club_popular: "Popular",
    club_select: "Select",
    club_selected: "Selected",
    club_setup_title: "Setup Your Subscription",
    club_setup_sub: "Complete subscription in just 3 steps",
    club_step_1: "Style & Frequency",
    club_step_2: "Details",
    club_step_3: "Confirm & Pay",
    club_step_style_title: "1. Select Bouquet Style",
    club_step_freq_title: "2. Delivery Frequency",
    club_btn_next: "Enter Details (Next Step)",
    club_delivery_info: "3. Delivery Details",
    club_recipient_name: "Recipient Full Name",
    club_recipient_name_placeholder: "e.g. Ali Mammadov",
    club_phone: "Contact Phone",
    club_phone_placeholder: "e.g. +994 50 123 45 67",
    club_address: "Delivery Address",
    club_address_placeholder: "e.g. Nasimi district, Samad Vurgun street, house 45, apt 12",
    club_date: "First Delivery Date",
    club_btn_prev: "Back",
    club_btn_next_summary: "Next (Summary)",
    club_step_confirm_title: "4. Confirm & Pay",
    club_confirm_sub: "Subscription Confirmation:",
    club_confirm_desc: "Renewal will be done automatically in each payment period for the selected plan. First delivery will be executed in the upcoming days.",
    club_confirm_tip: "Our florist will create a bouquet of the freshest seasonal flowers every time.",
    club_btn_activate: "Activate Subscription",
    club_btn_activating: "Activating...",
    club_summary_title: "Order Summary",
    club_summary_plan: "Plan:",
    club_summary_style: "Style:",
    club_summary_freq: "Frequency:",
    club_summary_recipient: "Recipient:",
    club_summary_address: "Address:",
    club_summary_delivery: "Delivery:",
    club_summary_free: "Free",
    club_summary_total: "Total:",
    club_security_tip: "Your payments are secure. You can change or pause the plan at any time.",
  },
  uz: {
    home: "Bosh sahifa",
    collections: "Kolleksiyalar",
    club: "BirBuketClub",
    create_bouquet: "Guldasta yaratish",
    gardener: "BirBağban",
    about: "Biz haqimizda",
    bagban_panel: "Bog'bon paneli",
    florist_panel: "Florist paneli",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    logout: "Chiqish",
    profile: "Profil",
    cart: "Savat",
    profile_info: "Profil ma'lumotlarim",
    order_history: "Buyurtmalar tarixi",
    favorites: "Sevimlilarim",
    gardener_requests: "Bog'bon murojaatlari",
    services_title: "Xizmatlarimiz",
    services_subtitle: "Sizga eng yaxshi xizmatni taklif qilish uchun har bir detalga e'tibor qaratamiz.",
    loading_api: "API'dan ma'lumot yuklanmoqda...",
    
    // Hero Section
    premium_service: "Premium guldasta xizmati",
    hero_title_1: "Har bir gulda",
    hero_title_italic: "bir hikoya",
    hero_title_2: "bor",
    hero_desc: "Tabiiy gullar, estetik xona o'simliklari va unutilmas tadbirlaringiz uchun maxsus dizayn qilingan bezaklar. Muhabbatingizni gullar bilan ifodalaymiz.",
    order_now: "Hozir buyurtma berish",
    view_collections: "Kolleksiyalarni ko'rish",
    fresh_species: "45+ turdagi",
    fresh_desc: "Yangi kesilgan gul turlari har kuni omborda",

    // About Section
    about_title: "BirBuket - tuyg'ularning eng nozik ifodasi",
    about_desc: "BirBuket sifatida maqsadimiz - yaqinlaringizga yetkaziladigan har bir guldastani o'zgacha qilishdir. Platformamiz orqali tezda buyurtma berishingiz va yetkazib berish bosqichini osongina kuzatib borishingiz mumkin.",
    why_choose_us: "Nega bizni tanlashadi?",
    why_choose_li_1: "- Keng turdagi guldastalar va individual dizayn imkoniyati",
    why_choose_li_2: "- Qulay to'lov va oddiy buyurtma jarayoni",
    why_choose_li_3: "- Mijozlar mamnuniyatiga yo'naltirilgan qo'llab-quvvatlash xizmati",
    
    hl_title_1: "Yangi gullar",
    hl_desc_1: "Kompozitsiyalar har kuni tanlangan yangi gullardan tayyorlanadi.",
    hl_title_2: "Tezkor yetkazib berish",
    hl_desc_2: "Boku bo'ylab yetkazib berish: masofaga qarab 5–20 AZN (4 kmgacha 5 AZN; 15 kmdan ortiq 20 AZN). O'z vaqtida va xavfsiz yetkazib berish.",
    hl_title_3: "Individual yondashuv",
    hl_desc_3: "Har bir guldasta sizning xohishingizga ko'ra did bilan shakllantiriladi.",
    hl_title_4: "Ishonchli xizmat",
    hl_desc_4: "Buyurtmadan topshirishgacha bo'lgan har bir qadamda shaffof jarayon.",

    // Footer Section
    footer_desc: "Bokudagi eng yangi va sifatli gullarning yagona manzili. Yaqinlaringizni xursand qilish uchun biz shu yerdamiz.",
    catalog: "Katalog",
    services: "Xizmatlar",
    support: "Qo'llab-quvvatlash",
    write_to_us: "Bizga yozing",
    newsletter_desc: "Yangiliklar va aksiyalardan xabardor bo'ling.",
    all_products: "Barcha mahsulotlar",
    toy_decor: "Nikoh bezaklari",
    faq: "Savollar",
    delivery_rules: "Yetkazib berish qoidalari",
    returns: "Qaytarish",
    contact: "Aloqa",
    rights_reserved: "© 2024 BirBuket. Barcha huquqlar himoyalangan.",
    privacy_policy: "Maxfiylik siyosati",
    terms_of_use: "Foydalanish shartlari",

    // Auth / Login & Register
    login_heading: "Akkauntga kirish",
    login_sub: "Davom etish uchun elektron pochta va parolni kiriting",
    email_or_user: "Email yoki foydalanuvchi nomi",
    email_or_user_placeholder: "Email yoki username",
    password_label: "Parol",
    forgot_password: "Parolni unutdingizmi?",
    remember_me: "Meni eslab qol",
    dont_have_account: "Akkauntingiz yo'qmi?",
    signup_link: "Ro'yxatdan o'ting",
    login_hero_title: "Yaqinlaringiz uchun gul tanlang va buyurtmani osongina kuzating",
    login_hero_desc: "BirBuket akkauntingiz bilan guldasta tanlang, manzilni kiriting va yetkazib berish holatini bosqichma-bosqich kuzatib boring.",
    login_feat_1: "Buyurtmalar tarixini shaxsiy akkauntda to'plang",
    login_feat_2: "Manzil, qabul qiluvchi va yetkazib berish eslatmalarini boshqaring",
    login_feat_3: "Holatni kuzating: tayyorlanmoqda, yo'lda, yetkazildi",
    login_feat_4: "Onlayn to'lov va buyurtma tafsilotlarini bir teginishda ko'ring",

    name_label: "Ism",
    surname_label: "Familiya",
    name_placeholder: "Ismingiz",
    surname_placeholder: "Familiyangiz",
    gender_label: "Jins",
    gender_male: "Erkak",
    gender_female: "Ayol",
    birth_date_label: "Tug'ilgan sana",
    username_label: "Foydalanuvchi nomi",
    phone_label: "Telefon raqami",
    email_label: "Elektron pochta",
    password_confirm_label: "Parolni tasdiqlang",
    register_heading: "Ro'yxatdan o'tish",
    register_sub: "BirBuket oilasiga qo'shiling",
    register_btn: "Hisob yaratish",
    already_have_account: "Akkauntingiz bormi?",
    login_link: "Kirish",

    // BirBuketClub
    club_title: "BirBuketClub",
    club_subscriptions: "Obunalar",
    club_flowers: "Gullar",
    club_studio: "Studio",
    club_sub_desc: "Gul obunasi bilan har hafta yoki har oy eshigingizga keladigan yangi gullar quvonchini his eting.",
    club_sub_title: "Uyingizga har doim tarovat kelsin",
    club_btn_start: "Hozir boshla",
    club_btn_setup: "Obunani sozlash",
    club_active_plan: "Faol reja:",
    club_subscribers: "1200+ Obunachi",
    club_plans_title: "Obuna rejalari",
    club_plans_sub: "Ehtiyojingizga mosini tanlang",
    club_popular: "Ommabop",
    club_select: "Tanlash",
    club_selected: "Tanlandi",
    club_setup_title: "Obunangizni sozlang",
    club_setup_sub: "Atigi 3 qadamda obunani yakunlang",
    club_step_1: "Uslub va chastota",
    club_step_2: "Ma'lumotlar",
    club_step_3: "Tasdiqlash va to'lov",
    club_step_style_title: "1. Guldasta uslubini tanlang",
    club_step_freq_title: "2. Yetkazib berish chastotasi",
    club_btn_next: "Ma'lumotlarni kiritish (keyingi qadam)",
    club_delivery_info: "3. Yetkazib berish ma'lumotlari",
    club_recipient_name: "Qabul qiluvchining ismi va familiyasi",
    club_recipient_name_placeholder: "Masalan, Ali Mammedov",
    club_phone: "Aloqa telefoni",
    club_phone_placeholder: "Masalan, +994 50 123 45 67",
    club_address: "Yetkazib berish manzili",
    club_address_placeholder: "Masalan, Nasimiy tumani, Samad Vurgun ko'chasi, 45-uy, 12-kvartira",
    club_date: "Birinchi yetkazib berish sanasi",
    club_btn_prev: "Orqaga",
    club_btn_next_summary: "Oldinga (xulosa)",
    club_step_confirm_title: "4. Tasdiqlash va to'lov",
    club_confirm_sub: "Obunani tasdiqlash:",
    club_confirm_desc: "Tanlangan reja bo'yicha har bir to'lov davrida avtomatik ravishda yangilanish amalga oshiriladi. Birinchi yetkazib berish yaqin kunlarda amalga oshiriladi.",
    club_confirm_tip: "Floristimiz har safar eng yangi mavsumiy gullardan guldasta tayyorlaydi.",
    club_btn_activate: "Obunani faollashtirish",
    club_btn_activating: "Faollashtirilmoqda...",
    club_summary_title: "Buyurtma xulosasi",
    club_summary_plan: "Reja:",
    club_summary_style: "Uslub:",
    club_summary_freq: "Chastota:",
    club_summary_recipient: "Qabul qiluvchi:",
    club_summary_address: "Manzil:",
    club_summary_delivery: "Yetkazib berish:",
    club_summary_free: "Bepul",
    club_summary_total: "Jami:",
    club_security_tip: "To'lovlaringiz xavfsiz. Istalgan vaqtda rejani o'zgartirishingiz yoki to'xtatishingiz mumkin.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'az' || saved === 'ru' || saved === 'en' || saved === 'uz') {
      return saved as Language;
    }
    return 'az';
  });

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: keyof typeof translations['az']): string => {
    return translations[language][key] || translations['az'][key] || '';
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
